### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\acer\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json'

### ISSUE THREAD

**Issue by MyrzajanAsanbekov** [lvboda/vscode-img-fast#24] opened 2024-06-05 00:17 UTC

**Comment by lvboda** [comment] 2024-06-29 16:41
Thanks for reporting this. This issue is a duplicate of #13. Please follow the original issue for updates.

**Closed by lvboda** 2024-06-29 16:41 UTC
Labels: duplicate
