### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\ASUS\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json'

### ISSUE THREAD

**Issue by Aleqyan777** [lvboda/vscode-img-fast#20] opened 2024-03-29 17:16 UTC

**Comment by lvboda** [comment] 2024-06-29 16:43
Thanks for reporting this. This issue is a duplicate of #13. Please follow the original issue for updates.

**Closed by lvboda** 2024-06-29 16:43 UTC
Labels: duplicate
