### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\PSC\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json'

### ISSUE THREAD

**Issue by 01062004-boop** [lvboda/vscode-img-fast#25] opened 2024-06-18 07:11 UTC

**Comment by 01062004-boop** [comment] 2024-06-18 07:12
help

**Comment by lvboda** [comment] 2024-06-29 16:40
Thanks for reporting this. This issue is a duplicate of #13. Please follow the original issue for updates.

**Closed by lvboda** 2024-06-29 16:40 UTC
Labels: duplicate
