### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\Wilson\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json'

### ISSUE THREAD

**Issue by Digitalwonderfulstudio** [lvboda/vscode-img-fast#23] opened 2024-05-26 13:19 UTC
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Wonderful Studio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background: url('caminho/para/sua/imagem.jpg') no-repeat center center;
            background-size: cover;
            color: #fff;
            padding: 20px;
            text-align: center;
            position: relative;
        }
        header::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0, 0, 0, 0.5);
            z-index: 0;
        }
        header h1, header p {
            position: relative;
            z-index: 1;
            margin: 0;
        }
        nav {
            background-color: #444;
            padding: 10px 0;
            text-align: center;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
        }
        nav a:hover {
            background-color: #555;
        }
        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 0 20px;
        }
        .portfolio {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
        }
        .portfolio img {
            max-width: 100%;
            height: auto;
            border-radius: 50%;
        }
        .video {
            max-width: 100%;
            height: auto;
            border-radius: 20px;
            margin-bottom: 20px;
        }
        form {
            margin-top: 20px;
        }
        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        input[type="submit"] {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 5px;
        }
        input[type="submit"]:hover {
            background-color: #444;
        }
        .contact-info {
            margin-top: 20px;
        }
        .contact-info h3 {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

<header>
    <h1>Digital Wonderful Studio</h1>
    <p>Seu destino para fotografias excepcionais</p>
</header>

<nav>
    <a href="#home">Home</a>
    <a href="#gestante">Fotos de Gestante</a>
    <a href="#criancas">Fotos de Crianças</a>
    <a href="#aniversario">Fotos de Aniversário</a>
    <a href="#casamento">Fotos de Casamento</a>
    <a href="#ar-livre">Fotos ao Ar Livre</a>
    <a href="#graduacao">Fotos de Graduação</a>
    <a href="#contact">Contato</a>
</nav>

<div class="container">
    <section id="home">
        <h2>Bem-vindo ao Digital Wonderful Studio</h2>
        <p>Explore nosso portfólio de fotografias excepcionais.</p>
    </section>

    <section id="gestante">
        <h2>Fotos de Gestante</h2>
        <div class="portfolio">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 1">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 2">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 3">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 4">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 5">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 6">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 7">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 8">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 9">
            <img src="https://via.placeholder.com/300" alt="Foto de Gestante 10">
        </div>
        <div class="video">
            <video controls>
                <source src="Design sem nome.mp4" type="video/mp4">
                Seu navegador não suporta a tag de vídeo.
            </video>
        </div>
    </section>

    <section id="criancas">
        <h2>Fotos de Crianças</h2>
        <div class="portfolio">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 1">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 2">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 3">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 4">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 5">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 6">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 7">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 8">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 9">
            <img src="https://via.placeholder.com/300" alt="Foto de Criança 10">
        </div>
        <div class="video">
            <video controls>
                <source src="video-criancas.mp4" type="video/mp4">
                Seu navegador não suporta a tag de vídeo.
            </video>
        </div>
    </section>

    <section id="aniversario">
        <h2>Fotos de Aniversário</h2>
        <div class="portfolio">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 1">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 2">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 3">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 4">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 5">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 6">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 7">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 8">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 9">
            <img src="https://via.placeholder.com/300" alt="Foto de Aniversário 10">
        </div>
        <div class="video">
            <video controls>
                <source src="video-aniversario.mp4" type="video/mp4">
                Seu navegador não suporta a tag de vídeo.
            </video>
        </div>
    </section>

    <section id="casamento">
        <h2>Fotos de Casamento</h2>
        <div class="portfolio">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 1">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 2">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 3">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 4">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 5">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 6">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 7">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 8">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 9">
            <img src="https://via.placeholder.com/300" alt="Foto de Casamento 10">
        </div>
        <div class="video">
            <video controls>
                <source src="video-casamento.mp4" type="video/mp4">
                Seu navegador não suporta a tag de vídeo.
            </video>
        </div>
    </section>

    <section id="ar-livre">
        <h2>Fotos ao Ar Livre</h2>
        <div class="portfolio">
            <img src="" alt="Foto ao Ar Livre 1">
            <img src="DWS (100).jpg" alt="Foto ao Ar Livre 2">
            <img src="DWS (103).jpg" alt="Foto ao Ar Livre 3">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 4">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 5">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 6">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 7">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 8">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 9">
            <img src="https://via.placeholder.com/150" alt="Foto ao Ar Livre 10">
        </div>
        <div class="video">
            <video controls>
                <source src="MVI_3523.MP4" type="video/mp4">
            </video>
        </div>
    </section>

    <section id="graduacao">
        <h2>Fotos de Graduação</h2>
        <div class="portfolio">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 1">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 2">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 3">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 4">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 5">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 6">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 7">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 8">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 9">
            <img src="https://via.placeholder.com/300" alt="Foto de Graduação 10">
        </div>
        <div class="video">
            <video controls>
                <source src="video-graduacao.mp4" type="video/mp4">
                Seu navegador não suporta a tag de vídeo.
            </video>
        </div>
    </section>

    <section id="contact">
        <h2>Entre em Contato</h2>
        <form action="#" method="post">
            <input type="text" name="name" placeholder="Seu Nome" required>
            <input type="text" name="email" placeholder="Seu E-mail" required>
            <textarea name="message" placeholder="Sua Mensagem" rows="4" required></textarea>
            <input type="submit" value="Enviar Mensagem">
        </form>
        <div class="contact-info">
            <h3>Contatos da Empresa</h3>
            <p>Email: contato@digitalwonderfulstudio.com</p>
            <p>Telefone: (11) 1234-5678</p>
            <p>WhatsApp: (11) 98765-4321</p>
            <h3>Funcionários</h3>
            <p>João Silva: (11) 91234-5678</p>
            <p>Maria Oliveira: (11) 97654-3210</p>
        </div>
    </section>
</div>

</body>
</html>

**Comment by lvboda** [comment] 2024-06-29 16:41
Thanks for reporting this. This issue is a duplicate of #13. Please follow the original issue for updates.

**Closed by lvboda** 2024-06-29 16:41 UTC
Labels: duplicate
