### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\USUARIO\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json'

### ISSUE THREAD

**Issue by gyutaro12** [lvboda/vscode-img-fast#18] opened 2023-12-24 16:05 UTC
porque me sale error si quiero hacer un fondo de la página. ayudaaaaa

**Comment by lvboda** [comment] 2024-06-29 16:43
Thanks for reporting this. This issue is a duplicate of #13. Please follow the original issue for updates.

**Closed by lvboda** 2024-06-29 16:43 UTC
Labels: duplicate
