### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c: \Users\b2pay\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json

### ISSUE THREAD

**Issue by teambet2pay** [lvboda/vscode-img-fast#13] opened 2023-06-14 13:00 UTC

**Comment by lvboda** [comment] 2023-06-17 05:58
Hello, can you provide the steps to reproduce the bug?

**Comment by lvboda** [comment] 2024-06-29 16:49
Related issue: #25, #24, #23, #22, #21, #20, #19, #18 (closed as duplicate)

**Closed** 2024-06-29 16:59 UTC
Labels: bug

**Comment by lvboda** [comment] 2024-06-29 17:17
Please upgrade to version `1.0.4` and verify that the issue is resolved. If you encounter any further problems, feel free to open a new issue.
<br>
Thank you for your contribution and for helping us improve our project.

**Comment by lvboda** [comment] 2024-06-29 17:21
Closed this issues as fixed in version `1.0.4`.
